// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tpl-x/echo/internal/config"
	"github.com/tpl-x/echo/internal/logger"
)

// Injectors from wire.go:

// wireApp init for builder backend
func wireApp(conf *config.AppConfig) *app {
	zapLogger := logger.NewZapLogger(conf)
	mainApp := newApp(conf, zapLogger)
	return mainApp
}
